version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/tools"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
