run:
  concurrency: 8
  issues-exit-code: 1
  tests: true

linters-settings:
  decorder:
    dec-order:
      - const
      - type
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: false
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/alexandear/import-gitlab-commits)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  godot:
    scope: all
    capital: true
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 140
  misspell:
    locale: US
  tenv:
    all: true

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - err113
    - nonamedreturns
    - gomnd
    - rowserrcheck
    - wastedassign
    - paralleltest
    - testpackage
