name: Security Scan

on:
  schedule:
    # Once a month on the 1st at 1PM UTC
    - cron: "0 13 1 * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  vulncheck:
    name: Scan for vulnerabilities in Go code
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
