name: Security Scan

on:
  schedule:
    # Once a month on the 1st at 1PM UTC
    - cron: "0 13 1 * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  vulncheck:
    name: Scan for vulnerabilities in Go code
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: stable
